apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.5.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"  # Cambia esta contraseña según tus necesidades
          resources:
            limits:
              memory: "512Mi"  # Limita la memoria a 512 MB
              cpu: "500m"      # Limita el uso de CPU a 50% de un núcleo
            requests:
              memory: "256Mi"  # Reserva 256 MB de memoria
              cpu: "250m"      # Reserva el uso de CPU a 25% de un núcleo
          volumeMounts:
            - name: grafana-dashboard-volume
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.json
              subPath: dashboard.json  # Especifica el subPath para el archivo
      volumes:
        - name: grafana-dashboard-volume
          configMap:
            name: grafana-dashboard  # Hace referencia al ConfigMap del dashboard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
data:
  dashboard.json: |
    {
      "dashboard": {
        "panels": [
          {
            "type": "graph",
            "title": "CPU Usage",
            "targets": [
              {
                "expr": "rate(cpu_usage_seconds_total[1m])",
                "legendFormat": "{{instance}}"
              }
            ]
          }
        ]
      }
    }
