apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.37.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          resources:
            limits:
              memory: "1Gi"  # Limita la memoria a 1 GB
              cpu: "1"       # Limita el uso de CPU a 1 núcleo
            requests:
              memory: "512Mi"  # Reserva 512 MB de memoria
              cpu: "500m"      # Reserva el uso de CPU a 50% de un núcleo
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
