apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: franklinmamanim921/recomendacion:latest 
          ports:
            - containerPort: 5001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  ports: 
  - port: 5001 
    targetPort: 5001 
    nodePort: 31838
  selector:
    app: recommendation-service
  type: NodePort
