apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000  # Asigna un puerto para acceder fuera del clúster
  type: NodePort  # Cambiar de ClusterIP a NodePort
