
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  ports:
    - port: 5001
      targetPort: 5001
    - port: 5001  # Asegúrate de exponer el puerto de métricas
      targetPort: 5001
  selector:
    app: recommendation-service
  type: NodePort
