apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      nodePort: 31838  # Asegúrate de que nodePort esté correctamente configurado
  selector:
    app: recommendation-service
