
apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31068  # Si usas NodePort
  selector:
    app: vote-app
  type: NodePort  # Cambia a LoadBalancer si tu proveedor de nube lo soporta