apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31068  # Asegúrate de que nodePort esté correctamente configurado
  selector:
    app: vote-app
